# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FE

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: qat

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Setup Frontend Lock File Path
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Use .env.qat file
        run: |
          cd /root/ai-image/fe/_work/ai_images_app/ai_images_app
          cp .env.qat .env

      - name: Configure Frontend Dependencies
        run: |
          cd /root/ai-image/fe/_work/ai_images_app/ai_images_app
          npm install
          npm run build
          pm2 del fe || true
          pm2 start npm --name "fe" -- start
          pm2 save
